### ISSUE TITLE
Is autolocks groups working?

### ISSUE THREAD

**Issue by KMKoushik** [ken-okabe/vscode-markdown-note#1]
Hey hey.

Is the autoLockGroups settings work for you? I tried to clone your project and test it and it doesn't seem to work. Am I missing something? Can you please help me?

**Comment by ken-okabe** [comment]
Yeah, when I release this, things need a documentation since the configuration is a bit tricky.

![image](https://github.com/ken-okabe/vscode-markdown-note/assets/1316994/b1eed770-6b20-465a-b31e-12755f3903ca)

![image](https://github.com/ken-okabe/vscode-markdown-note/assets/1316994/a87f9336-143a-4eec-8d8c-08c2f1335d7d)


   "workbench.editor.autoLockGroups": {
        
        "mainThreadWebview-MarkdownNote": true,

        "default": false,
        "workbench.editorinputs.searchEditorInput": false,
        "jupyter-notebook": false,
        "imagePreview.previewEditor": false,
        "vscode.audioPreview": false,
        "vscode.videoPreview": false,
        "jsProfileVisualizer.cpuprofile.table": false,
        "jsProfileVisualizer.heapprofile.table": false,
        "terminalEditor": true,
        "workbench.input.interactive": false,
        "mainThreadWebview-markdown.preview": false
    },

You need to add
` "mainThreadWebview-MarkdownNote": true,` 
manually because there is no way to do this programatically from the extensions.

I observe you have joined the issue
https://github.com/microsoft/vscode/issues/125791
and yes, it works but I have changed the ID from `showNote` to `MarkdownNote` because the old ID is too common.

**Comment by KMKoushik** [comment]
Thanks, That's what I'am missing then. I thought it will automatically add it. Thanks for your help

**Comment by ken-okabe** [comment]
NP, by the way, I will "reload" this repository soon, for publishing as ver. 1.0.0
